const projects = [
  {
    name: "Bomb Sniffer",
    image: "bombSnifferImg",
    desc: "This is a project using an API to simulate the game minesweeper.",
    liveUrl: "https://bomb-sniffer-garrettanderson.netlify.com",
    githubUrl: "https://github.com/GarrettAnderson/bomb-sniffer",
    hasGit: true,
  },
  {
    name: "Bomb Sniffer",
    image: "bombSnifferImg",
    desc: "This is a project using an API to simulate the game minesweeper.",
    liveUrl: "https://bomb-sniffer-garrettanderson.netlify.com",
    githubUrl: "https://github.com/GarrettAnderson/bomb-sniffer",
    hasGit: true,
  },
  {
    name: "Bomb Sniffer",
    image: "bombSnifferImg",
    desc: "This is a project using an API to simulate the game minesweeper.",
    liveUrl: "https://bomb-sniffer-garrettanderson.netlify.com",
    githubUrl: "https://github.com/GarrettAnderson/bomb-sniffer",
    hasGit: true,
  },
  {
    name: "Bomb Sniffer",
    image: "bombSnifferImg",
    desc: "This is a project using an API to simulate the game minesweeper.",
    liveUrl: "https://bomb-sniffer-garrettanderson.netlify.com",
    githubUrl: "https://github.com/GarrettAnderson/bomb-sniffer",
    hasGit: true,
  },
  {
    name: "Bomb Sniffer",
    image: "bombSnifferImg",
    desc: "This is a project using an API to simulate the game minesweeper.",
    liveUrl: "https://bomb-sniffer-garrettanderson.netlify.com",
    githubUrl: "https://github.com/GarrettAnderson/bomb-sniffer",
    hasGit: true,
  },
  {
    name: "Bomb Sniffer",
    image: "bombSnifferImg",
    desc: "This is a project using an API to simulate the game minesweeper.",
    liveUrl: "https://bomb-sniffer-garrettanderson.netlify.com",
    githubUrl: "https://github.com/GarrettAnderson/bomb-sniffer",
    hasGit: true,
  },
];
